#
# Module manifest for module 'PowerShellCookbook'
#
# Generated by: Lee Holmes
#
# Generated on: 3/29/2009
#

@{

ModuleToProcess = 'PowerShellCookbook.psm1'

# Version number of this module.
ModuleVersion = '1.3.1'

# ID used to uniquely identify this module
GUID = '695122f6-fd0a-4869-9af1-c59f86310b1a'

# Author of this module
Author = 'Lee Holmes'

# Company or vendor of this module
CompanyName = 'Lee Holmes'

# Copyright statement for this module
Copyright = '(c) 2009 Lee Holmes. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Sample scripts from the Windows PowerShell Cookbook'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '3.0'

}